#!/bin/bash
#Usage:
#source Msg
#out 'E' "error"
#-------or---------
#sh Msg E "error"

#debug 4, info 3, warning 2, error 1, fatal 0
DEBUG_LEVEL=3

function out(){
    local D=`date +%F~%T`
    if [ $# -eq 0 ];then
            echo "${D}"
    else
	case "$1" in
	'D'|'d')
		if [ $DEBUG_LEVEL -ge 4 ];then
                	echo -e "${D}\033[34m DEBUG\033[0m: $2"
		fi
		;;
	'I'|'i')
		if [ $DEBUG_LEVEL -ge 3 ];then
	                echo -e "${D}\033[1;34m INFO\033[0m: $2"
		fi
		;;
	'W'|'w')
		if [ $DEBUG_LEVEL -ge 2 ];then
        	        echo -e "${D}\033[1;37m WARNING\033[0m: $2"
		fi
		;;
	'E'|'e')
		if [ $DEBUG_LEVEL -ge 1 ];then
                	echo -e "${D}\033[1;31m ERROR\033[0m: $2"
		fi
		;;
	'F'|'f')
		if [ $DEBUG_LEVEL -ge 0 ];then
	                echo -e "${D}\033[1;31;5m FATAL\033[0m: $2"
		fi
		;;
	'H'|'h')
                echo -e "Usage:  Msg [OPTION] [MESSAGE]
                OPTIONS:
                \033[34mD|d\033[0m	for debug
                \033[1;34mI|i\033[0m	for information (default)
                \033[1;37mW|w\033[0m	for warning
                \033[1;31mE|e\033[0m	for error
                \033[1;31;5mF|f\033[0m	for fatal
                H|h       for help

		Now debug level is ${DEBUG_LEVEL}
                ${D}
        	"
		;;
        *)
		if [ $DEBUG_LEVEL -ge 3 ];then
	                echo -e "${D}\033[1;34m INFO\033[0m: $1"
		fi
		;;
	esac
    fi
}

out "$@"
