#!/bin/sh
###
 # @Author: JiHan
 # @Date: 2020-12-10 17:25:38
 # @LastEditTime: 2020-12-15 14:58:10
 # @LastEditors: JiHan
 # @Description: Scan all files in a dir or dirs.
 #               Default path is ./
 # @Usage: 
 #      1. Add processing method to file_do()
 #      2. like: 
 #          $ chmod +x scanfiles
 #          $ ls -F < scanfiles ./
### 

files=
OLD_IFS="$IFS"
IFS=" "
tmp=($@)
IFS="$OLD_IFS"
lpath=$(cd $(dirname $0); pwd)
num=0

function file_do(){
    file=$1
    # Do something...
    echo $file
}

function scandir() {
    local cur_dir parent_dir workdir
    workdir=$1
    cd ${workdir}
    if [ ${workdir} = "/" ]
    then
        cur_dir=""
    else
        cur_dir=$(pwd)
    fi  

    for dirlist in $(ls ${cur_dir})
    do  
        if test -d ${dirlist};then
            cd ${dirlist}
            scandir ${cur_dir}/${dirlist}
            cd ..
        else
            files=${files}" "${cur_dir}/${dirlist}
            file_do ${cur_dir}/${dirlist}
        fi  
    done
}

if [ $# -lt 1 ];then
    scandir ${lpath}
else 
  while [ $num -lt $# ]
  do
        if test -d "${tmp[$num]}"
        then
            scandir ${tmp[$num]}
        elif test -f "${tmp[$num]}"
        then
            files=${files}" "${tmp[$num]}
            file_do ${tmp[$num]}
        else
            echo "${tmp[$num]} isn't exist, pls input a new one!!"
        fi  
        num=$(($num+1))
  done
fi
#  echo $files

