apiVersion: v1
kind: ConfigMap
metadata:
    name: redis-cluster-config
data:
    redis.conf: |
        cluster-enabled yes
        cluster-config-file /data/nodes.conf
        cluster-node-timeout 5000
